/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto.tela_views;

import br.com.projeto.modelo.Clientes;
import br.com.projeto.DAO.ClientesDAO;
import br.com.projeto.DAO.FornecedoresDAO;
import br.com.projeto.DAO.ProdutosDAO;
import br.com.projeto.modelo.Fornecedores;
import br.com.projeto.modelo.Produtos;
import br.com.projeto.modelo.Utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author camil
 */
public class Formulario_Produtos extends javax.swing.JFrame {

    //Metodo para Listar na tabela
    public void listar() {
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listarProdutos(); //criando uma lista de clientes que vai receber o listar Clintes, onde retorna a lista
        DefaultTableModel dados = (DefaultTableModel) TabelaProdutos.getModel(); //criação do objeto que vai armazenar os dados dessa lista para exibição na tabela de clientes
        dados.setNumRows(0); //limpa os dados

        for (Produtos c : lista) { //para cada item da lista vai criar um obj chamado c 
            dados.addRow(new Object[]{
                //definição de ordem para aparecer na tabela
                c.getId(),
                c.getDescricao(),
                c.getPreco(),
                c.getQtd_estoque(),
                c.getFornecedor().getNome()  //ele vai receber as informacoes do fornecedor e só vai aparecer o nome do fornecedor
            }); //retorno de objetos

        }

    }

    /**
     * Creates new form Formulario_Cliente
     */
    public Formulario_Produtos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelDados = new javax.swing.JPanel();
        cod = new javax.swing.JLabel();
        jTextcod = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        jTextdescricao = new javax.swing.JTextField();
        jTextPreco = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        uf = new javax.swing.JLabel();
        btBusca2 = new javax.swing.JButton();
        cbFornecedor = new javax.swing.JComboBox();
        jTextEstoque = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTpesquisa2 = new javax.swing.JTextField();
        CCnm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProdutos = new javax.swing.JTable();
        btPesquisar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        painelDados.setBackground(new java.awt.Color(255, 255, 255));

        cod.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cod.setText("CÓDIGO:");

        jTextcod.setEditable(false);
        jTextcod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nome.setText("DESCRIÇÃO:");

        jTextdescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextdescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextdescricaoKeyPressed(evt);
            }
        });

        jTextPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        email.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        email.setText("PREÇO:");

        celular.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        celular.setText("QUANTIDADE EM ESTOQUE:");

        uf.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        uf.setText("FORNECEDOR:");

        btBusca2.setBackground(new java.awt.Color(153, 153, 153));
        btBusca2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBusca2.setText("Pesquisar");
        btBusca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBusca2ActionPerformed(evt);
            }
        });

        cbFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbFornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbFornecedorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFornecedorMouseClicked(evt);
            }
        });
        cbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFornecedorActionPerformed(evt);
            }
        });

        jTextEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addComponent(cod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextcod, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosLayout.createSequentialGroup()
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosLayout.createSequentialGroup()
                                .addComponent(nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextdescricao))
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(celular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(btBusca2)
                        .addGap(526, 526, 526))))
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addComponent(uf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod)
                    .addComponent(jTextcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(jTextdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBusca2))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celular)
                    .addComponent(jTextEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uf)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(226, 226, 226))
        );

        jTabbedPane1.addTab("Dados do Produto", painelDados);

        jTpesquisa2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTpesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpesquisa2ActionPerformed(evt);
            }
        });
        jTpesquisa2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTpesquisa2KeyPressed(evt);
            }
        });

        CCnm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CCnm.setText("NOME:");

        TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "PREÇO", "ESTOQUE", "FORNECEDOR"
            }
        ));
        TabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaProdutos);

        btPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        btPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        btPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btPesquisarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CCnm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTpesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTpesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCnm)
                    .addComponent(btPesquisar))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Produtos", jPanel3);

        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(btNovo)
                .addGap(40, 40, 40)
                .addComponent(btSalvar)
                .addGap(27, 27, 27)
                .addComponent(btEditar)
                .addGap(36, 36, 36)
                .addComponent(btExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btSalvar)
                    .addComponent(btNovo)
                    .addComponent(btEditar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
       new Utilitarios().Limpatela(painelDados);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // botão para salvar
        Produtos obj = new Produtos();

       obj.setDescricao(jTextdescricao.getText());
       obj.setPreco(Double.parseDouble(jTextPreco.getText()));
       obj.setQtd_estoque(Integer.parseInt(jTextEstoque.getText()));
       
       //Objeto de Fornecedor
       Fornecedores f = new Fornecedores();
       f = (Fornecedores)cbFornecedor.getSelectedItem();    //o objeto do selectItem é capturado e converte(castting) em um objeto fornecedor armazenando no f  
       obj.setFornecedor(f);

        ProdutosDAO dao = new ProdutosDAO();

        dao.cadastrarProdutos(obj);
        
        new Utilitarios().Limpatela(painelDados);


    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // botão excluir

        Produtos obj = new Produtos();

        obj.setId(Integer.parseInt(jTextcod.getText()));

       ProdutosDAO dao = new ProdutosDAO();

        dao.excluirProdutos(obj);
        
        new Utilitarios().Limpatela(painelDados);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
           
            String nome = jTextdescricao.getText();
               Clientes obj = new Clientes();
               ClientesDAO dao = new ClientesDAO();
               
               obj = dao.ConsultaPorNome(nome);
               
               if(obj.getNome() != null ){
               
               
               //Exibe os dados do obj nos campos de texto
               jTextcod.setText(String.valueOf(obj.getId()));
               jTextdescricao.setText(obj.getNome());
              
               jTextPreco.setText(obj.getEmail());
              
              cbFornecedor.setSelectedItem(obj.getUf());
               }
               else{
                   JOptionPane.showMessageDialog(null, "Produto não encontrado");
               }

        
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // botão editar

        Produtos obj = new Produtos();

        obj.setId(Integer.parseInt(jTextcod.getText()));
        obj.setDescricao(jTextdescricao.getText());
        obj.setPreco(Double.parseDouble(jTextPreco.getText()));
        obj.setQtd_estoque(Integer.parseInt(jTextEstoque.getText()));
            
            //cria um obj de fornecedor 
        Fornecedores f = new Fornecedores();
        f = (Fornecedores)cbFornecedor.getSelectedItem(); //fornecedor selecionado no obj é armazenado
        
        obj.setFornecedor(f);   //passa o obj para o produto
       
        ProdutosDAO dao = new ProdutosDAO();
        dao.alterarProdutos(obj);
        
        new Utilitarios().Limpatela(painelDados);
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btBusca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusca2ActionPerformed
            // botão buscar cliente por nome
           String nome = jTextdescricao.getText();
                Produtos obj = new Produtos();
               ProdutosDAO dao = new ProdutosDAO();
               
               obj = dao.ConsultaPorNome(nome);
               
               cbFornecedor.removeAllItems();
               
               if(obj.getDescricao() != null ){
               
               
               //Exibe os dados do obj nos campos de texto
               jTextcod.setText(String.valueOf(obj.getId()));
               jTextdescricao.setText(obj.getDescricao());
               jTextPreco.setText(String.valueOf(obj.getPreco()));
               jTextEstoque.setText(String.valueOf(obj.getQtd_estoque()));
              
               
               Fornecedores f = new Fornecedores();
               FornecedoresDAO fdao = new FornecedoresDAO();
               
               f = fdao.ConsultaPorNome(obj.getFornecedor().getNome());
               
               cbFornecedor.getModel().setSelectedItem(f);
               }
               else{
                   JOptionPane.showMessageDialog(null, "Produto não encontrado");
               }  
                   
    }//GEN-LAST:event_btBusca2ActionPerformed

    private void cbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFornecedorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carregar a lista
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaProdutosMouseClicked
        // Pegar os dados pessoais armazenados
        jTabbedPane1.setSelectedIndex(0); //Passa para outra aba, cujo seu indice é 0

        jTextcod.setText(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 0).toString());
        jTextdescricao.setText(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 1).toString());
        jTextPreco.setText(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 2).toString());
        jTextEstoque.setText(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 3).toString());
        
        Fornecedores f = new Fornecedores();
        FornecedoresDAO dao = new FornecedoresDAO();
        
        f = dao.ConsultaPorNome(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 3).toString());  //pega o texto da coluna, faz a consulta por nome, retorna um objeto e armazena no f
        
        cbFornecedor.removeAllItems();
        cbFornecedor.setSelectedItem(f);
        
    }//GEN-LAST:event_TabelaProdutosMouseClicked

    private void jTpesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpesquisa2ActionPerformed
           


    }//GEN-LAST:event_jTpesquisa2ActionPerformed

    private void jTpesquisa2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesquisa2KeyPressed
          String nome = "%" +jTpesquisa2.getText()+ "%";   
        
       ProdutosDAO dao = new ProdutosDAO();
       List<Produtos> lista = dao.BuscarProdutosPorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) TabelaProdutos.getModel(); //criação do objeto que vai armazenar os dados dessa lista para exibição na tabela de clientes
        dados.setNumRows(0); //limpa os dados

        for (Produtos c : lista) { //para cada item da lista vai criar um obj chamado c 
            dados.addRow(new Object[]{
                //definição de ordem para aparecer na tabela
                c.getId(),
                c.getDescricao(),
                c.getPreco(),
                c.getQtd_estoque(),
                c.getFornecedor().getNome()
            });
        }      

    }//GEN-LAST:event_jTpesquisa2KeyPressed

    private void btPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btPesquisarKeyPressed

    }//GEN-LAST:event_btPesquisarKeyPressed

    private void cbFornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbFornecedorAncestorAdded
        // TODO add your handling code here:
        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> listadefornecedores = dao.listarFornecedores();
        cbFornecedor.removeAll();    //evita duplicação
        
        for(Fornecedores f: listadefornecedores){
            cbFornecedor.addItem(f);
        }
    }//GEN-LAST:event_cbFornecedorAncestorAdded

    private void jTextdescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextdescricaoKeyPressed
       String nome = "%" +jTpesquisa2.getText()+ "%";   
        
       ProdutosDAO dao = new ProdutosDAO();
       List<Produtos> lista = dao.BuscarProdutosPorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) TabelaProdutos.getModel(); //criação do objeto que vai armazenar os dados dessa lista para exibição na tabela de clientes
        dados.setNumRows(0); //limpa os dados

        for (Produtos c : lista) { //para cada item da lista vai criar um obj chamado c 
            dados.addRow(new Object[]{
                //definição de ordem para aparecer na tabela
                c.getId(),
                c.getDescricao(),
                c.getPreco(),
                c.getQtd_estoque(),
                c.getFornecedor().getNome()
            });
        }      
    }//GEN-LAST:event_jTextdescricaoKeyPressed

    private void cbFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFornecedorMouseClicked
        // limpa e permite alterar o fornecedor
        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> listadefornecedores = dao.listarFornecedores();
        cbFornecedor.removeAll();    //evita duplicação
        
        for(Fornecedores f: listadefornecedores){
            cbFornecedor.addItem(f);
        }
         
    }//GEN-LAST:event_cbFornecedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCnm;
    public javax.swing.JTable TabelaProdutos;
    private javax.swing.JButton btBusca2;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JLabel celular;
    private javax.swing.JLabel cod;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextEstoque;
    private javax.swing.JTextField jTextPreco;
    private javax.swing.JTextField jTextcod;
    private javax.swing.JTextField jTextdescricao;
    private javax.swing.JTextField jTpesquisa2;
    private javax.swing.JLabel nome;
    private javax.swing.JPanel painelDados;
    private javax.swing.JLabel uf;
    // End of variables declaration//GEN-END:variables
}
