/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto.tela_views;

import br.com.projeto.DAO.ItemVendaDAO;
import br.com.projeto.DAO.ProdutosDAO;
import br.com.projeto.DAO.VendasDAO;
import br.com.projeto.modelo.Clientes;
import br.com.projeto.modelo.ItemVenda;
import br.com.projeto.modelo.Produtos;
import br.com.projeto.modelo.Vendas;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author camil
 */
public class Formulario_Pagamentos extends javax.swing.JFrame {

    Clientes cliente = new Clientes();
    DefaultTableModel carrinho;

    /**
     * Creates new form Formulario_Pagamentos
     */
    public Formulario_Pagamentos() {
        initComponents();

        jTdinheiro.setText("0");
        jTcartao.setText("0");
        jTBOLETO.setText("0");
        jTroco.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cod = new javax.swing.JLabel();
        jTBOLETO = new javax.swing.JTextField();
        cod1 = new javax.swing.JLabel();
        cod2 = new javax.swing.JLabel();
        cod3 = new javax.swing.JLabel();
        cod4 = new javax.swing.JLabel();
        jTotalpag = new javax.swing.JTextField();
        jTroco = new javax.swing.JTextField();
        jTdinheiro = new javax.swing.JTextField();
        jTcartao = new javax.swing.JTextField();
        jButtonFinalizar = new javax.swing.JButton();
        cod5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextObservacao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamentos");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Pagamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        cod.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        cod.setText("OBSERVAÇÃO:");

        jTBOLETO.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTBOLETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBOLETOActionPerformed(evt);
            }
        });

        cod1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        cod1.setText("BOLETO:");

        cod2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        cod2.setText("TROCO:");

        cod3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        cod3.setText("TOTAL:");

        cod4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        cod4.setText("CARTÃO:");

        jTotalpag.setEditable(false);
        jTotalpag.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTotalpag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalpagActionPerformed(evt);
            }
        });

        jTroco.setEditable(false);
        jTroco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrocoActionPerformed(evt);
            }
        });

        jTdinheiro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTdinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdinheiroActionPerformed(evt);
            }
        });

        jTcartao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTcartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcartaoActionPerformed(evt);
            }
        });

        jButtonFinalizar.setBackground(new java.awt.Color(153, 153, 153));
        jButtonFinalizar.setText("Finalizar Venda");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        cod5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        cod5.setText("DINHEIRO:");

        jTextObservacao.setColumns(20);
        jTextObservacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextObservacao.setRows(5);
        jScrollPane1.setViewportView(jTextObservacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cod4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTcartao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cod5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cod2)
                                        .addComponent(cod1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTBOLETO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTroco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(cod3)
                        .addGap(32, 32, 32)
                        .addComponent(jTotalpag, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cod)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cod5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cod4)
                            .addComponent(jTcartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod1)
                            .addComponent(jTBOLETO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod2)
                            .addComponent(jTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotalpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod3))
                .addGap(18, 18, 18)
                .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTBOLETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBOLETOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBOLETOActionPerformed

    private void jTotalpagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalpagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalpagActionPerformed

    private void jTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrocoActionPerformed

    private void jTdinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdinheiroActionPerformed

    private void jTcartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcartaoActionPerformed

    }//GEN-LAST:event_jTcartaoActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        double pcartao, pcheque, pdinheiro, totalpago, totalvenda, troco; //recebem os valores que o usuario digitar

        pcartao = Double.parseDouble(jTcartao.getText());
        pcheque = Double.parseDouble(jTBOLETO.getText());
        pdinheiro = Double.parseDouble(jTdinheiro.getText());
        totalvenda = Double.parseDouble(jTotalpag.getText());

        //Calculo do troco e do total
        totalpago = pcartao + pcheque + pdinheiro;
        troco = totalpago - totalvenda;

        jTroco.setText(String.valueOf(troco)); //exibe o troco pro usuario

        Vendas objv = new Vendas();
        //dados do cliente(cliente_id)
        objv.setCliente(cliente);

        //data da venda
        Date agora = new Date(); // obj que vai pegar a dat atual do sistema
        SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy-MM-dd"); // mascara de formatação do obj
        String datamysql = dataEUA.format(agora);

        objv.setData_venda(datamysql);
        //Total da venda e obs
        objv.setTotal_vendas(totalvenda);
        objv.setObs(jTextObservacao.getText());

        VendasDAO dao_v = new VendasDAO();
        dao_v.cadastrarVenda(objv);

        //retorno do id da ultima venda
        objv.setId(dao_v.retornaUltimaVenda());

        //cadastro de produtos na tabela itemvendas
        for (int i = 0; i < carrinho.getRowCount(); i++) {
            
            int qtd_estoque, qtd_comprada, qtd_atualizada;
            Produtos objp = new Produtos();
            ProdutosDAO dao_produtos = new ProdutosDAO();
            
            ItemVenda item = new ItemVenda();
            item.setVenda(objv);

            objp.setId(Integer.parseInt(carrinho.getValueAt(i, 0).toString()));
            item.setProduto(objp);
            item.setQtd(Integer.parseInt(carrinho.getValueAt(i, 2).toString()));
            item.setSubtotal(Double.parseDouble(carrinho.getValueAt(i, 4).toString()));

            
            //Baixa no estoque
            qtd_estoque = dao_produtos.retornaEstoqueAtual(objp.getId());
            qtd_comprada = Integer.parseInt(carrinho.getValueAt(i,2).toString());
            qtd_atualizada = qtd_estoque - qtd_comprada;
                    
             dao_produtos.baixarEstoque(objp.getId(),qtd_atualizada);       
                    
            ItemVendaDAO daoitem = new ItemVendaDAO();
            daoitem.cadastraItem(item);

        }
        
        JOptionPane.showMessageDialog(null, "Venda registrada com sucesso!");
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Pagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cod;
    private javax.swing.JLabel cod1;
    private javax.swing.JLabel cod2;
    private javax.swing.JLabel cod3;
    private javax.swing.JLabel cod4;
    private javax.swing.JLabel cod5;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBOLETO;
    private javax.swing.JTextField jTcartao;
    private javax.swing.JTextField jTdinheiro;
    private javax.swing.JTextArea jTextObservacao;
    public javax.swing.JTextField jTotalpag;
    private javax.swing.JTextField jTroco;
    // End of variables declaration//GEN-END:variables
}
