/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto.tela_views;

import br.com.projeto.DAO.ClientesDAO;
import br.com.projeto.DAO.FornecedoresDAO;
import br.com.projeto.modelo.Clientes;
import br.com.projeto.modelo.Fornecedores;
import br.com.projeto.modelo.Utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author camil
 */
public class Formulario_Fornecedores extends javax.swing.JFrame {

    //Metodo para Listar na tabela
    public void listar() {
        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> lista = dao.listarFornecedores(); //criando uma lista de clientes que vai receber o listar Clintes, onde retorna a lista
        DefaultTableModel dados = (DefaultTableModel) TabelaFornecedores.getModel(); //criação do objeto que vai armazenar os dados dessa lista para exibição na tabela de clientes
        dados.setNumRows(0); //limpa os dados

        for (Fornecedores c : lista) { //para cada item da lista vai criar um obj chamado c 
            dados.addRow(new Object[]{
                //definição de ordem para aparecer na tabela
                c.getId(),
                c.getNome(),
                c.getCnpj(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereço(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()
            }); //retorno de objetos

        }

    }

    /**
     * Creates new form Formulario_Cliente
     */
    public Formulario_Fornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelDados = new javax.swing.JPanel();
        cod = new javax.swing.JLabel();
        jTextcod = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        jCel = new javax.swing.JFormattedTextField();
        tel = new javax.swing.JLabel();
        jTel = new javax.swing.JFormattedTextField();
        cep = new javax.swing.JLabel();
        jFcep = new javax.swing.JFormattedTextField();
        jendereco = new javax.swing.JTextField();
        endereco = new javax.swing.JLabel();
        jTnum = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        jTbairro = new javax.swing.JTextField();
        bairro = new javax.swing.JLabel();
        jTcidade = new javax.swing.JTextField();
        cidade = new javax.swing.JLabel();
        jTcomplem = new javax.swing.JTextField();
        complemento = new javax.swing.JLabel();
        uf = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        jFCNPJ = new javax.swing.JFormattedTextField();
        btBusca2 = new javax.swing.JButton();
        cbuf = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jTpesquisa2 = new javax.swing.JTextField();
        CCnm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFornecedores = new javax.swing.JTable();
        btPesquisar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Fornecedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        painelDados.setBackground(new java.awt.Color(255, 255, 255));

        cod.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cod.setText("CÓDIGO:");

        jTextcod.setEditable(false);
        jTextcod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nome.setText("NOME:");

        jTextNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomeKeyPressed(evt);
            }
        });

        jTextEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        email.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        email.setText("E-MAIL:");

        celular.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        celular.setText("CELULAR:");

        try {
            jCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCelActionPerformed(evt);
            }
        });

        tel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tel.setText("TELEFONE FIXO:");

        try {
            jTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelActionPerformed(evt);
            }
        });

        cep.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cep.setText("CEP:");

        try {
            jFcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFcep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFcepActionPerformed(evt);
            }
        });
        jFcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFcepKeyPressed(evt);
            }
        });

        jendereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        endereco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        endereco.setText("ENDEREÇO:");

        jTnum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnumActionPerformed(evt);
            }
        });

        numero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        numero.setText("NÚMERO:");

        jTbairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbairroActionPerformed(evt);
            }
        });

        bairro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bairro.setText("BAIRRO:");

        jTcidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcidadeActionPerformed(evt);
            }
        });

        cidade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cidade.setText("CIDADE:");

        jTcomplem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTcomplem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcomplemActionPerformed(evt);
            }
        });

        complemento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        complemento.setText("COMPLEMENTO:");

        uf.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        uf.setText("UF:");

        rg.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rg.setText("CNPJ:");

        try {
            jFCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCNPJ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFCNPJActionPerformed(evt);
            }
        });

        btBusca2.setBackground(new java.awt.Color(153, 153, 153));
        btBusca2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBusca2.setText("Pesquisar");
        btBusca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBusca2ActionPerformed(evt);
            }
        });

        cbuf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA ", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbufActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosLayout.createSequentialGroup()
                        .addComponent(bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTbairro, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(complemento)
                        .addGap(18, 18, 18)
                        .addComponent(jTcomplem, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addComponent(cep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFcep, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(endereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTnum, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addComponent(cod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextcod, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosLayout.createSequentialGroup()
                                        .addComponent(nome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextNome))
                                    .addGroup(painelDadosLayout.createSequentialGroup()
                                        .addComponent(email)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelDadosLayout.createSequentialGroup()
                                        .addComponent(celular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btBusca2)))
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addComponent(rg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod)
                    .addComponent(jTextcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBusca2))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celular)
                    .addComponent(jCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel)
                    .addComponent(jTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTnum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(endereco)
                        .addComponent(jendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero)))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairro)
                    .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade)
                    .addComponent(jTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complemento)
                    .addComponent(jTcomplem)
                    .addComponent(uf)
                    .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rg)
                    .addComponent(jFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );

        jTabbedPane1.addTab("Dados Pessoais", painelDados);

        jTpesquisa2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTpesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpesquisa2ActionPerformed(evt);
            }
        });
        jTpesquisa2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTpesquisa2KeyPressed(evt);
            }
        });

        CCnm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CCnm.setText("NOME:");

        TabelaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "CNPJ", "E-MAIL", "TELEFONE", "CELULAR", "CEP", "ENDEREÇO", "NÚMERO", "COMPLEMENTO", "BAIRRO", "CIDADE", "UF"
            }
        ));
        TabelaFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaFornecedores);

        btPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        btPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        btPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btPesquisarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CCnm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTpesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTpesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCnm)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Fornecedores", jPanel3);

        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(btNovo)
                .addGap(40, 40, 40)
                .addComponent(btSalvar)
                .addGap(27, 27, 27)
                .addComponent(btEditar)
                .addGap(36, 36, 36)
                .addComponent(btExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btSalvar)
                    .addComponent(btNovo)
                    .addComponent(btEditar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTcomplemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcomplemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcomplemActionPerformed

    private void jTcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcidadeActionPerformed

    private void jTbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbairroActionPerformed

    private void jTnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnumActionPerformed

    private void jFcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFcepActionPerformed

    private void jTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelActionPerformed

    private void jCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCelActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
       new Utilitarios().Limpatela(painelDados);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // botão para salvar
        Fornecedores obj = new Fornecedores();

        obj.setNome(jTextNome.getText());
        obj.setCnpj(jFCNPJ.getText());
        obj.setEmail(jTextEmail.getText());
        obj.setTelefone(jTel.getText());
        obj.setCelular(jCel.getText());
        obj.setCep(jFcep.getText());
        obj.setEndereço(jendereco.getText());
        obj.setNumero(Integer.parseInt(jTnum.getText()));
        obj.setComplemento(jTcomplem.getText());
        obj.setBairro(jTbairro.getText());
        obj.setCidade(jTcidade.getText());
        obj.setUf(cbuf.getSelectedItem().toString());

        FornecedoresDAO dao = new FornecedoresDAO();

        dao.cadastrarFornecedores(obj);
        
        new Utilitarios().Limpatela(painelDados);


    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // botão excluir

        Fornecedores obj = new Fornecedores();

        obj.setId(Integer.parseInt(jTextcod.getText()));

        FornecedoresDAO dao = new FornecedoresDAO();

        dao.excluirFonecedor(obj);
        
        new Utilitarios().Limpatela(painelDados);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
            String nome = "%" +jTpesquisa2.getText()+ "%";  //inicio de qualquer carcter + minha pesquisa + qualquer carcater

        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> lista = dao.BuscarFornecedoresPorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) TabelaFornecedores.getModel(); //criação do objeto que vai armazenar os dados dessa lista para exibição na tabela de clientes
        dados.setNumRows(0); //limpa os dados

        for (Fornecedores c : lista) { //para cada item da lista vai criar um obj chamado c 
            dados.addRow(new Object[]{
                //definição de ordem para aparecer na tabela
                c.getId(),
                c.getNome(),
                c.getCnpj(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereço(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()
            }); //retorno de objetos

        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // botão editar

        Fornecedores obj = new Fornecedores();

        obj.setNome(jTextNome.getText());
        obj.setCnpj(jFCNPJ.getText());
        obj.setEmail(jTextEmail.getText());
        obj.setTelefone(jTel.getText());
        obj.setCelular(jCel.getText());
        obj.setCep(jFcep.getText());
        obj.setEndereço(jendereco.getText());
        obj.setNumero(Integer.parseInt(jTnum.getText()));
        obj.setComplemento(jTcomplem.getText());
        obj.setBairro(jTbairro.getText());
        obj.setCidade(jTcidade.getText());
        obj.setUf(cbuf.getSelectedItem().toString());

        obj.setId(Integer.parseInt(jTextcod.getText()));

        FornecedoresDAO dao = new FornecedoresDAO();
        
        dao.alterarFornecedor(obj);
        
        new Utilitarios().Limpatela(painelDados);
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void jFCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFCNPJActionPerformed

    private void btBusca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusca2ActionPerformed
            // botão buscar cliente por nome
            
               String nome = jTextNome.getText();
               Fornecedores obj = new Fornecedores();
               FornecedoresDAO dao = new FornecedoresDAO();
               
               obj = dao.ConsultaPorNome(nome);
               
               if(obj.getNome() != null ){
               
               
               //Exibe os dados do obj nos campos de texto
               jTextcod.setText(String.valueOf(obj.getId()));
               jTextNome.setText(obj.getNome());
               jFCNPJ.setText(obj.getCnpj());
               
               jTextEmail.setText(obj.getEmail());
               jTel.setText(obj.getTelefone());
               jCel.setText(obj.getCelular());
               
               jFcep.setText(obj.getCep());
               jendereco.setText(obj.getEndereço());
               jTnum.setText(String.valueOf(obj.getNumero()));
               jTcomplem.setText(obj.getComplemento());
               jTbairro.setText(obj.getBairro());
               jTcidade.setText(obj.getCidade());
               cbuf.setSelectedItem(obj.getUf());
               }
               else{
                   JOptionPane.showMessageDialog(null, "Cliente não encontrado");
               }
                   
    }//GEN-LAST:event_btBusca2ActionPerformed

    private void cbufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbufActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carregar a lista
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TabelaFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaFornecedoresMouseClicked
        // Pegar os dados pessoais armazenados
        jTabbedPane1.setSelectedIndex(0); //Passa para outra aba, cujo seu indice é 0

        jTextcod.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 0).toString());
        jTextNome.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 1).toString());
        jFCNPJ.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 2).toString());
        jTextEmail.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 3).toString());
        jTel.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 4).toString());
        jCel.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 5).toString());
        jFcep.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 6).toString());
        jendereco.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 7).toString());
        jTnum.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 8).toString());
        jTcomplem.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 9).toString());
        jTbairro.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 10).toString());
        jTcidade.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 11).toString());
        cbuf.setSelectedItem(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 12).toString());

    }//GEN-LAST:event_TabelaFornecedoresMouseClicked

    private void jTpesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpesquisa2ActionPerformed
           


    }//GEN-LAST:event_jTpesquisa2ActionPerformed

    private void jTpesquisa2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesquisa2KeyPressed
        String nome = "%" +jTpesquisa2.getText()+ "%";  //inicio de qualquer carcter + minha pesquisa + qualquer carcater

        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> lista = dao.BuscarFornecedoresPorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) TabelaFornecedores.getModel(); //criação do objeto que vai armazenar os dados dessa lista para exibição na tabela de clientes
        dados.setNumRows(0); //limpa os dados

        for (Fornecedores c : lista) { //para cada item da lista vai criar um obj chamado c 
            dados.addRow(new Object[]{
                //definição de ordem para aparecer na tabela
                c.getId(),
                c.getNome(),
                c.getCnpj(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereço(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()
            }); //retorno de objetos

        }

    }//GEN-LAST:event_jTpesquisa2KeyPressed

    private void btPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btPesquisarKeyPressed

    }//GEN-LAST:event_btPesquisarKeyPressed

    private void jFcepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFcepKeyPressed
            //Programacao do keypress
	
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //se o cliente clicar enter
         Clientes obj =  new Clientes();              // cria o objeto
         ClientesDAO dao = new ClientesDAO();
         obj = dao.buscaCep(jFcep.getText());
            //preenche os campos
         jendereco.setText(obj.getEndereço());
         jTbairro.setText(obj.getBairro());
         jTcidade.setText(obj.getCidade());
         cbuf.setSelectedItem(obj.getUf());               
         System.out.println(obj.getUf());
         
     }
    }//GEN-LAST:event_jFcepKeyPressed

    private void jTextNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCnm;
    private javax.swing.JTable TabelaFornecedores;
    private javax.swing.JLabel bairro;
    private javax.swing.JButton btBusca2;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbuf;
    private javax.swing.JLabel celular;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel cod;
    private javax.swing.JLabel complemento;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JFormattedTextField jCel;
    private javax.swing.JFormattedTextField jFCNPJ;
    private javax.swing.JFormattedTextField jFcep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JTextField jTcidade;
    private javax.swing.JTextField jTcomplem;
    private javax.swing.JFormattedTextField jTel;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextcod;
    private javax.swing.JTextField jTnum;
    private javax.swing.JTextField jTpesquisa2;
    private javax.swing.JTextField jendereco;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numero;
    private javax.swing.JPanel painelDados;
    private javax.swing.JLabel rg;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel uf;
    // End of variables declaration//GEN-END:variables
}
